config/routes.rb
Rails.application.routes.draw do
  namespace :authentication, path: '', as: '' do
    resources :users, only: %i[new create], path: '/register', path_names: { new: '/' }
    resources :sessions, only: %i[new create destroy], path: '/login', path_names: { new: '/' }
  end
  
  resources :favorites, only: %i[index create destroy], param: :product_id
  resources :users, only: :show, path: '/user', param: :username
  resources :categories, except: :show
  resources :products, path: '/'
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :products, dependent: :restrict_with_exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authorize!

  def index
    @categories = Category.all.order(name: :asc)
  end

  def new
    @category = Category.new
  end

  def edit
    category
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_url, notice: t('.created')
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def update
    if category.update(category_params)
      redirect_to categories_url, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: t('.destroyed') }
    end
  end

  private
    
    def category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="p-4 mb-4 text-center mx-auto">
  <p class="text-lg font-bold mb-2"><%= category.name %></p>
  <%= link_to t('.edit'), edit_category_path(category), class: "text-yellow-500 hover:text-yellow-700 mr-2" %>
  <%= link_to t('.delete'), category_path(category), data: { turbo_method: :delete,
turbo_confirm: t('common.confirm') }, class: "text-red-500 hover:text-red-700" %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% @category.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>

  <div>
    <%= form.label :name, class: "block text-sm font-bold mb-2" %>
    <%= form.text_field :name, class: "rounded mb-2" %>
  </div>

  <div class="mt-4">
    <%= form.submit "Update", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-2xl font-bold my-4"><%= t('.title') %></h1>

<%= render "form", category: @category %>

<div class="my-4">
  <%= link_to t('common.back'), categories_path, class: "font-bold text-teal-500" %>
</div>

app/views/categories/index.html.erb
<h1 class="text-3xl font-bold my-4 text-center"><%= t('.title') %></h1>

<%= render partial: 'category', collection: @categories %>

<div class="flex justify-center my-4">
  <%= link_to t('.new'), new_category_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
</div>

app/views/categories/new.html.erb
<h1 class="text-2xl font-bold my-4"><%= t('.title') %></h1>

<%= render "form", category: @category %>

<div class="my-4">
  <%= link_to t('common.back'), categories_path, class: "font-bold text-teal-500" %>
</div>