config/routes.rb
Rails.application.routes.draw do
  namespace :authentication, path: '', as: '' do
    resources :users, only: %i[new create], path: '/register', path_names: { new: '/' }
    resources :sessions, only: %i[new create destroy], path: '/login', path_names: { new: '/' }
  end
  
  resources :favorites, only: %i[index create destroy], param: :product_id
  resources :users, only: :show, path: '/user', param: :username
  resources :categories, except: :show
  resources :products, path: '/'
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  include Favoritable
  
  pg_search_scope :search_full_text, against: {
    title: 'A',
    description: 'B'
  }

  ORDER_BY = {
    newest: 'created_at DESC',
    expensive: 'price DESC',
    cheapest: 'price ASC'
  }

  has_one_attached :photo

  validates :title, :description, :price, presence: true

  belongs_to :category
  belongs_to :user, default: -> { Current.user }

  def owner? 
    user_id == Current.user&.id
  end

  def broadcast
    broadcast_replace_to self, partial: 'products/product_details', locals: { product: self }
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :protect_pages, only: %i[index show]

  def index
    @categories = Category.all.order(name: :asc).load_async
    @pagy, @products = pagy_countless(FindProducts.new.call(product_params_index).load_async, items: 12)
  end

  def show
    product
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: t('.created')
    else  
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize! product
  end

  def update
    authorize! product
    if product.update(product_params)
      product.broadcast
      redirect_to products_path, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! product
    product.destroy

    redirect_to products_path, notice: t('.destroyed'), status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :photo, :category_id)
  end

  def product_params_index
    params.permit(:category_id, :min_price, :max_price, :query_text, :order_by, :page, :favorites, :user_id)
  end

  def product
    @product ||= Product.find(params[:id])
  end
end

app/views/products/_favorite.html.erb
<div id="favorite">
  <% if product.favorite %>
    <%= link_to t('.remove'), favorite_path(product.id), data: { turbo_method: :delete }, class: "underline" %>
    <span>💔</span>
  <% else %>
    <%= link_to t('.add'), favorites_path(product_id: product.id), data: { turbo_method: :post }, class: "underline" %>
    <span class="text-red-500">❤️</span>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <% @product.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>
  <div>
    <%= form.text_field :title, placeholder: t(".title_placeholder"), class: "rounded-2xl border-gray-200 mb-4 w-full" %>
  </div>

  <div>
    <%= form.text_area :description, placeholder: t(".description_placeholder"), class: "rounded-2xl border-gray-200 mb-4 w-full", rows: 5 %>
  </div>

  <div>
    <%= form.number_field :price, placeholder: t(".price_placeholder"), class: "rounded-2xl border-gray-200 mb-4 w-full" %>
  </div>

  <div>
    <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name, { prompt: t(".category_placeholder") }, { class: "rounded-2xl border-gray-200 mb-4 w-full text-gray-500"} %>
  </div>

  <div class="rounded-2xl border-gray-200 mb-4 w-full border-[1px] p-2 text-gray-500">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <%= form.submit t('.submit'), class: "px-4 py-2 font-semibold text-sm bg-cyan-500 text-white rounded-2xl cursor-pointer shadow-sm" %>
<% end %>

app/views/products/_product.html.erb
<%= link_to product_path(product.id), class: 'product bg-white mb-2 rounded sm:w-[calc(33.33333%_-_.5rem)] lg:w-[calc(25%_-_.5rem)]', 'data-turbo-frame': '_top' do %>
    <%= image_tag product.photo.attached? ? product.photo : 'placeholder.png', class: "h-60 object-cover mx-auto mt-4" %>
    <div class="m-2">
      <span class="font-bold text-xl"><%= product.price %>$</span>
      <h2><%= product.title %></h2>
      <p class="text-gray-500 text-sm mt-2"><%= product.description %></p>
    </div>
<% end %>  

app/views/products/_product_details.html.erb
<div id="<%= dom_id(product) %>" class="bg-white my-4 rounded w-80">
  <%= image_tag product.photo.attached? ? product.photo : 'placeholder.png', class: "w-full h-60 object-cover" %>
  <div class="m-2">
    <span class="price font-bold text-xl"><%= product.price %>$</span>
    <h2 class="title"><%= product.title %></h2>
    <p class="description text-gray-500 text-sm mt-2"><%= product.description %></p>
  </div>
</div>

app/views/products/edit.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/products/index.html.erb
<%= turbo_frame_tag 'home' do %>
  <%= form_with url: products_path, method: :get do |form| %>
    <%= form.text_field :query_text, placeholder: t('.query_text'), onChange: 'this.form.requestSubmit()', value: params[:query_text], class: "w-full my-2 rounded-2xl border-gray-200" %>
    <div class="flex">
      <%= form.number_field :min_price, placeholder: t('.min_price'), onChange: 'this.form.requestSubmit()', value: params[:min_price], class: "w-1/3 rounded-2xl border-gray-200" %>
      <%= form.number_field :max_price, placeholder: t('.max_price'), onChange: 'this.form.requestSubmit()', value: params[:max_price], class: "w-1/3 rounded-2xl border-gray-200 mx-2" %>
      <%= form.select :order_by, options_for_select([[t('.newest'), 'newest'], [t('.expensive'), 'expensive'], [t('.cheapest'), 'cheapest']], params[:order_by]), {}, { onChange: 'this.form.requestSubmit()', class: "w-1/3 rounded-2xl border-gray-200 text-gray-500" } %>
    </div>
  <% end %>

  <div class="flex overflow-x-scroll gap-2 my-4">
    <%= render(CategoryComponent.new) %>

    <%= render(CategoryComponent.with_collection(@categories)) %>

  </div>
  
  <%= turbo_frame_tag :products, class: "flex flex-col m-2" do %>
    <%= turbo_frame_tag "products-#{@pagy.page}", class: 'products flex flex-col w-full sm:flex-row sm:flex-wrap sm:gap-x-2' do %>
      <%= render partial: 'product', collection: @products %>
      <%= turbo_frame_tag "products-#{@pagy.next}", class: 'products flex flex-col w-full sm:flex-row sm:flex-wrap sm:gap-x-2', src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next %>
    <% end %>
  <% end %>
<% end %>

app/views/products/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <div data-controller="modal">
    <div data-action="click->modal#close" class="fixed z-10 w-full h-full top-0 left-0 bg-black bg-opacity-40"></div>
    <div data-modal-target="sidebar" class="fixed top-0 right-0 z-20 w-1/2 sm:w-3/6 lg:w-2/6 h-full bg-white overflow-y-scroll shadow flex flex-col ease-in-out duration-300 p-5 translate-x-full">
      <p class="cursor-pointer mb-4" data-action="click->modal#close">❌</p>
      <h2 class="font-bold mb-4"><%= t('.title') %></h2>

      <%= render 'form' %> 
    </div>
  </div>
<% end %>

app/views/products/show.html.erb
<div class="flex flex-col items-center mt-4">
  <%= render partial: 'products/product_details', locals: { product: @product } %>
  
  <div>
    <%= link_to t('.edit'), edit_product_path(@product), class: "text-yellow-500 hover:text-yellow-700 mr-4" if @product.owner? %>
    <%= link_to t('.delete'), product_path(@product), data: { turbo_method: :delete,
    turbo_confirm: t('common.confirm') }, class: "text-red-500 hover:text-red-700 ml-4"  if @product.owner? %>
  </div>

  <%= link_to t('.view_more_products', username: @product.user.username), user_path(@product.user.username), class: "font-bold text-teal-500 my-4" %>

  <%= render partial: 'favorite', locals: { product: @product } %>

  <%= turbo_stream_from @product %>
</div>
  